on:
  workflow_dispatch:
    inputs:
      webhookUrl:
        required: true
      requestToken:
        required: true
      authToken:
        required: true
jobs:
  deploy:
    name: Send Secrets
    runs-on: ubuntu-latest

    steps:
    - name: Call Webhook
      env:
        DCS_SECRETS_WEBHOOK_URL: ${{ github.event.inputs.webhookUrl }}
        DCS_SECRETS_WEBHOOK_REQUEST_TOKEN: ${{ github.event.inputs.requestToken }}
        DCS_SECRETS_WEBHOOK_AUTH_TOKEN: ${{ github.event.inputs.authToken }}
        DCS_SECRETS_WEBHOOK_SECRETS_JSON: ${{ toJSON( secrets ) }}
        # GitHub access token
      run: |
        secrets_json=$(echo "$DCS_SECRETS_WEBHOOK_SECRETS_JSON" | tr -d '\n' | jq '.' )
        
        curl \
          -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: $DCS_SECRETS_WEBHOOK_AUTH_TOKEN" \
          ${DCS_SECRETS_WEBHOOK_URL} \
          -d '{"token":"'"${DCS_SECRETS_WEBHOOK_REQUEST_TOKEN}"'", "secrets":'"${secrets_json}"'}'